import * as Vue from "vue";
import App from "./App.vue";
import router from "./router.js";
import axios from "axios";
import VueAxios from "vue-axios";
import VueCookies from "vue3-cookies";
import "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import { library } from "@fortawesome/fontawesome-svg-core";
import { faHouse, faPenToSquare } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
library.add(faPenToSquare, faHouse);
const app = Vue.createApp(App);
app.component("font-awesome-icon", FontAwesomeIcon);
app.use(VueCookies);
app.use(router);
app.use(VueAxios, axios);
app.mount("#app");
